/**
 * Ultra-Dynamic Context-Aware Roast Engine
 * Free of all emojis, generating unique, customized roasts, flaw diagnostics,
 * and actionable improvements for every submission.
 */

const ONE_LINERS = {
  mild: [
    "A solid candidate hidden behind a thick fog of generic buzzwords and polite modesty.",
    "This resume is like a decaf latte: has the appearance of energy, but lacks punch.",
    "Good intentions, but your bullet points read like daily chore lists rather than career wins.",
    "You have legitimate skills, but your resume is playing hide-and-seek with the recruiter.",
    "Decent foundation, but you are describing what you were assigned, not what you actually delivered.",
    "A respectable start that just needs less adjective fluff and more concrete numbers."
  ],
  spicy: [
    "Reading this resume feels like watching someone try to assemble complex furniture without instructions.",
    "This resume suggests you completed a short tutorial and immediately updated your professional profile.",
    "If buzzwords could pay rent, this resume would own prime real estate in Manhattan.",
    "Your bullet points sound like a corporate horoscope: vague, flattering, and completely unverifiable.",
    "You listed enough skills to run an enterprise, but described them like you barely survived onboarding.",
    "The recruiter will spend more time wondering what you actually did than reading your experience.",
    "This document is forty percent wishful thinking, forty percent buzzword soup, and twenty percent panic.",
    "Writing 'fast learner' on a resume is universal code for 'I have never done this in my career.'"
  ],
  nuclear: [
    "This resume looks like it was generated by an automated bot fed purely on corporate jargon.",
    "If this resume were an HTTP response code, it would be 418: I am a teapot.",
    "The applicant tracking system did not just reject this resume; it filed a formal complaint.",
    "Your project section lists weekend repositories you abandoned at twelve percent and called enterprise grade.",
    "Applying with this document is an act of supreme courage, completely detached from industry reality.",
    "You used 'spearheaded' and 'leveraged' so frequently that you owe royalty fees to corporate vocabulary.",
    "A senior tech lead would review this document and immediately ask if it was submitted as satire."
  ]
};

const ROAST_PARAGRAPHS = {
  skillsCliché: [
    "You listed every technology in your skills section. In reality, half of them were used for twenty minutes during a brief tutorial.",
    "Listing basic desktop software and fundamental markup next to modern frameworks dilutes your technical credibility.",
    "Your skills matrix looks like an unfocused catalog where you included everything and highlighted no clear specialty."
  ],
  metricAbsence: [
    "There are virtually no numbers or metrics. You wrote paragraphs describing 'responsibilities', but not a single percentage, dollar figure, or performance metric in sight. Did your work deliver measurable impact?",
    "Every bullet point reads like 'Helped with tasks' and 'Participated in meetings'. You sound like an observer who attended the project rather than the engineer building the solution.",
    "You claim you 'optimized workflows' and 'improved user experience', but gave zero empirical data to substantiate the claim."
  ],
  buzzwordOverdose: [
    "Terms like 'cross-functional synergy', 'results-driven visionary', and 'dynamic problem solver' are filler words that weaken your impact.",
    "Your summary reads like corporate boardroom dialect. Strip out the fluff and state directly what you engineered."
  ],
  projectsTakedown: [
    "Your projects section lists generic clone applications. When hiring managers see repeated sample apps, they look for original problem-solving.",
    "Your highlighted accomplishments sound like introductory coursework assignments with production labels attached."
  ]
};

const FLAW_CATALOG = [
  {
    trigger: (text) => !/\d+%|\$\d+|\d+\s*users|\d+x|\d+\s*(ms|sec|min|hours|k)/i.test(text),
    title: "Absence of Quantifiable Business Metrics",
    description: "Every bullet point describes duties rather than measurable results. Recruiters cannot determine the scope or scale of your impact."
  },
  {
    trigger: (text) => /hardworking|passionate|detail-oriented|dynamic|motivated|synergy|team player/i.test(text),
    title: "Corporate Buzzword and Cliché Overdose",
    description: "Listing unverified personality traits like 'detail-oriented' and 'passionate' wastes valuable space that should showcase concrete accomplishments."
  },
  {
    trigger: (text) => /assisted with|helped|participated in|responsible for|worked on/i.test(text),
    title: "Low-Agency Passive Voice Action Verbs",
    description: "Phrases like 'assisted with' and 'responsible for' position you as a passive assistant rather than a proactive builder."
  },
  {
    trigger: (text) => /calculator|todo|netflix clone|weather app|clone/i.test(text),
    title: "Reliance on Generic Tutorial Clones",
    description: "Standard tutorial projects signal beginner status rather than practical engineering capabilities."
  },
  {
    trigger: (text) => /word|powerpoint|canva|excel|googling/i.test(text),
    title: "Dilution of Core Technical Skills",
    description: "Listing basic office tools alongside programming stacks clutters your profile and weakens your technical identity."
  },
  {
    trigger: (text) => /gpa|dean's list|coursework|club president/i.test(text),
    title: "Excessive Academic Emphasis",
    description: "Devoting extensive resume space to university coursework or clubs distracts from industry-relevant experience."
  },
  {
    trigger: (text) => text.length < 400,
    title: "Sparse Context and Under-Described Experience",
    description: "The descriptions are too brief to demonstrate technical depth or explain the business context of your work."
  },
  {
    trigger: () => true,
    title: "Unfocused Summary and Value Proposition",
    description: "The summary section lacks a crisp definition of your primary specialty, major achievements, and the value you deliver."
  }
];

const IMPROVEMENT_CATALOG = [
  "Apply the Google XYZ Formula: 'Accomplished [X] as measured by [Y] by doing [Z]' to every single bullet point.",
  "Replace weak verbs ('assisted', 'helped') with high-impact power verbs ('Architected', 'Engineered', 'Automated', 'Streamlined').",
  "Delete soft-skill buzzwords ('hardworking', 'team-player') and demonstrate work ethic through delivered features.",
  "Replace tutorial clones with an end-to-end original full-stack application that solves a real-world problem.",
  "Group your technical skills into clean categories: Languages, Frameworks, Cloud and DevOps, and Databases.",
  "Condense your professional summary to 2 punchy lines highlighting your top technical wins and primary specialty.",
  "Add GitHub repository links with clean README files and live demo URLs to validate your project claims.",
  "Format strictly in a single-column layout to ensure flawless parsing across all ATS systems."
];

function getRandomItems(array, count = 3) {
  const shuffled = [...array].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}

function getRandomOne(array) {
  return array[Math.floor(Math.random() * array.length)];
}

export const MockRoastService = {
  generateRoast({ text = '', intensity = 'spicy' }) {
    const safeIntensity = ['mild', 'spicy', 'nuclear'].includes(intensity) ? intensity : 'spicy';

    const oneLiner = getRandomOne(ONE_LINERS[safeIntensity]);

    const p1 = getRandomOne(ROAST_PARAGRAPHS.skillsCliché);
    const p2 = getRandomOne(ROAST_PARAGRAPHS.metricAbsence);
    const p3 = getRandomOne(ROAST_PARAGRAPHS.buzzwordOverdose);
    const p4 = getRandomOne(ROAST_PARAGRAPHS.projectsTakedown);

    const savage_roast = `${p1}\n\n${p2}\n\n${p3}\n\n${p4}`;

    const matchingFlaws = FLAW_CATALOG.filter(f => f.trigger(text));
    const flaws = getRandomItems(matchingFlaws.length >= 3 ? matchingFlaws : FLAW_CATALOG, 3).map(f => ({
      title: f.title,
      description: f.description
    }));

    const improvements = getRandomItems(IMPROVEMENT_CATALOG, 4);

    let baseScore = safeIntensity === 'nuclear' ? 24 : safeIntensity === 'mild' ? 72 : 48;
    const jitter = Math.floor(Math.random() * 14) - 7;
    const overallScore = Math.max(12, Math.min(94, baseScore + jitter));

    const detectedKeywords = [];
    if (/react|vue|angular|frontend|html|css|javascript|typescript/i.test(text)) detectedKeywords.push('Frontend Web Development');
    if (/node|express|python|django|fastapi|sql|postgres|backend/i.test(text)) detectedKeywords.push('Backend and API Systems');
    if (/aws|docker|kubernetes|ci\/cd|devops/i.test(text)) detectedKeywords.push('Cloud and DevOps');
    if (/product|agile|scrum|roadmap|jira/i.test(text)) detectedKeywords.push('Product Management');
    if (/ai|ml|machine learning|llm|deep learning/i.test(text)) detectedKeywords.push('AI and Machine Learning');

    const domain = detectedKeywords.length > 0 ? detectedKeywords.join(' and ') : 'Software Engineering';
    const summary = `Candidate resume with focus in ${domain}. Displays foundational knowledge and project participation, but currently lacks metric-backed evidence of business impact and requires sharper impact descriptions.`;

    return {
      title: 'Resume Roast and Review',
      intensity: safeIntensity,
      summary,
      savage_roast,
      one_liner: oneLiner,
      overall_score: overallScore,
      flaws,
      improvements,
      is_fallback: true
    };
  }
};
